---
collections:
  - containers.podman
  - community.general
  - name: cephadm.ansible
    source: https://github.com/GreenCappuccino/cephadm-ansible.git
    type: git
    version: d0fa62a75b405ff258d6955d84cc298bd8670f69
