[project]
name = "awx-metal-chore"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "ansible>=8.7.0",
    "ansible-lint>=6.8.7",
]
