---
- name: Prepare k3s
  hosts: r710
  tasks:
    - name: Disable firewalld
      become: true
      ansible.builtin.systemd_service:
        name: firewalld
        state: stopped
        enabled: false
    - name: Ensure k3s directory exists
      become: true
      ansible.builtin.file:
        path: '/etc/rancher/k3s'
        mode: 0755
        state: directory
    - name: Ensure kubelet config exists
      become: true
      ansible.builtin.copy:
        content: |
          apiVersion: kubelet.config.k8s.io/v1beta1
          kind: KubeletConfiguration
          shutdownGracePeriod: 60m
          shutdownGracePeriodCriticalPods: 30m
          healthzBindAddress: 0.0.0.0
        dest: '/etc/rancher/k3s/kubelet.yaml'
        mode: '0644'
- name: Install k3s Server
  hosts: server
  become: true
  roles:
    - role: k3s.orchestration.k3s_server
  tags:
    - install
- name: Post-install steps
  hosts: k3s_cluster
  become: true
  tasks:
    - name: Ensure CNI directory exists
      become: true
      ansible.builtin.file:
        path: '/opt/cni/bin'
        mode: 0755
        state: directory
    - name: Install CNI plugins
      ansible.builtin.dnf:
        name: containernetworking-plugins
        state: present
    - name: Find executable files in /usr/libexec/cni
      ansible.builtin.find:
        paths: /usr/libexec/cni
        patterns: '*'
        file_type: file
        use_regex: no
        hidden: no
      register: cni_executables
    - name: Copy each found executable file
      ansible.builtin.copy:
        src: '{{ item.path }}'
        dest: /opt/cni/bin/
        owner: root
        group: root
        mode: '0755'
        remote_src: yes
      loop: '{{ cni_executables.files }}'
