---
- name: Install Cloudflare Tunnel using Podman
  hosts: r710
  tasks:
    - name: Pull cloudflare/cloudflared image
      become: true
      containers.podman.podman_image:
        name: docker.io/cloudflare/cloudflared:latest
        force: true
    - name: Run Cloudflare tunnel
      become: true
      containers.podman.podman_container:
        name: cftunnel
        image: docker.io/cloudflare/cloudflared:latest
        command: "tunnel --no-autoupdate run --token {{ cloudflare_tunnel_token }}"
        network: host
        volume:
          - /etc/cockpit/ws-certs.d/:/certificates:ro
        state: present
        recreate: true
        generate_systemd:
          path: /etc/systemd/system
          restart_policy: always
    - name: Enable and start service
      become: true
      ansible.builtin.systemd_service:
        name: container-cftunnel
        daemon-reload: true
        state: restarted
        enabled: true
