---
- name: Prepare k3s
  hosts: r710
  tasks:
    - name: Disable firewalld
      become: true
      ansible.builtin.systemd_service:
        name: firewalld
        state: stopped
        enabled: false
    - name: Ensure k3s directory exists
      become: true
      ansible.builtin.file:
        path: "/etc/rancher/k3s"
        mode: 0755
        state: directory
    - name: Ensure kubelet config exists
      become: true
      ansible.builtin.copy:
        content: |
          apiVersion: kubelet.config.k8s.io/v1beta1
          kind: KubeletConfiguration
          shutdownGracePeriod: 120s
          shutdownGracePeriodCriticalPods: 90s
          healthzBindAddress: 0.0.0.0
        dest: "/etc/rancher/k3s/kubelet.yaml"
        mode: "0644"
- name: Install k3s Server
  hosts: server
  become: true
  roles:
    - role: k3s.orchestration.k3s_server
