---
- name: SELinux permissive mode
  hosts: r710
  tasks:
    - name: Put SELinux in permissive mode, logging actions that would be blocked.
      become: true
      ansible.posix.selinux:
        policy: targeted
        state: permissive
