---
- name: Setup networking with nmcli
  hosts: r710
  become: true
  tasks:
    - name: Configure enp5s0f0 for publ
      community.general.nmcli:
        conn_name: enp5s0f0
        ifname: enp5s0f0
        type: ethernet
        ip4: '{{ publ_cidr }}'
        gw4: '{{ publ_gate }}'
        mtu: '{{ publ_mtu }}'
        dns4: '{{ dns_servers }}'
        dns4_ignore_auto: true
        method6: 'disabled'
        state: present
    - name: Configure enp5s0f1 for mana
      community.general.nmcli:
        conn_name: enp5s0f1
        ifname: enp5s0f1
        type: ethernet
        ip4: '{{ mana_cidr }}'
        mtu: '{{ mana_mtu }}'
        method6: 'disabled'
        state: present
    - name: Configure eno1 for clus
      community.general.nmcli:
        conn_name: eno1
        ifname: eno1
        type: ethernet
        ip4: '{{ clus_cidr }}'
        mtu: '{{ clus_mtu }}'
        method6: 'disabled'
        state: present
    - name: Configure eno2 for virt
      community.general.nmcli:
        conn_name: eno2
        ifname: eno2
        type: ethernet
        ip4: '{{ virt_cidr }}'
        mtu: '{{ virt_mtu }}'
        method6: 'disabled'
        state: present
    - name: Configure bond0 for ceph
      community.general.nmcli:
        conn_name: bond0
        ifname: bond0
        type: bond
        mode: balance-rr
        ip4: '{{ ceph_cidr }}'
        mtu: '{{ ceph_mtu }}'
        method6: 'disabled'
        state: present
    - name: Configure eno3 as bond0 slave
      community.general.nmcli:
        conn_name: bond0-slave1
        ifname: eno3
        type: bond-slave
        slave_type: bond
        master: bond0
        mtu: '{{ ceph_mtu }}'
        method6: 'disabled'
        state: present
    - name: Configure eno4 as bond0 slave
      community.general.nmcli:
        conn_name: bond0-slave2
        ifname: eno4
        type: bond-slave
        slave_type: bond
        master: bond0
        mtu: '{{ ceph_mtu }}'
        method6: 'disabled'
        state: present
# Similar issue to: https://serverfault.com/questions/1130379/how-to-configure-networkmanager-to-not-set-default-search-domain-in-rhel8-based
- name: Setup resolv.conf
  hosts: r710
  become: true
  tasks:
    - name: Create resolv.conf.manually-configured
      ansible.builtin.copy:
        content: |
          nameserver 1.1.1.1
          nameserver 1.0.0.1
        dest: /etc/resolv.conf.manually-configured
        mode: '0644'
    - name: Soft link resolv.conf to resolv.conf.manually-configured
      ansible.builtin.file:
        src: /etc/resolv.conf.manually-configured
        dest: /etc/resolv.conf
        state: link
