---
- name: Setup networking with nmcli
  hosts: r710
  become: true
  tasks:
    - name: Configure enp5s0f0 for publ
      community.general.nmcli:
        conn_name: enp5s0f0
        ifname: enp5s0f0
        type: ethernet
        ip4: '{{ publ_cidr }}'
        gw4: '{{ publ_gate }}'
        mtu: '{{ publ_mtu }}'
        method6: 'disabled'
        state: present
    - name: Configure enp5s0f1 for mana
      community.general.nmcli:
        conn_name: enp5s0f1
        ifname: enp5s0f1
        type: ethernet
        ip4: '{{ mana_cidr }}'
        mtu: '{{ mana_mtu }}'
        method6: 'disabled'
        state: present
    - name: Configure eno1 for clus
      community.general.nmcli:
        conn_name: eno1
        ifname: eno1
        type: ethernet
        ip4: '{{ clus_cidr }}'
        mtu: '{{ clus_mtu }}'
        method6: 'disabled'
        state: present
    - name: Configure eno2 for virt
      community.general.nmcli:
        conn_name: eno2
        ifname: eno2
        type: ethernet
        ip4: '{{ virt_cidr }}'
        mtu: '{{ virt_mtu }}'
        method6: 'disabled'
        state: present
    - name: Configure bond0 for ceph
      community.general.nmcli:
        conn_name: bond0
        ifname: bond0
        type: bond
        mode: balance-tlb
        ip4: '{{ ceph_cidr }}'
        mtu: '{{ ceph_mtu }}'
        method6: 'disabled'
        state: present
    - name: Configure eno3 as bond0 slave
      community.general.nmcli:
        conn_name: bond0-slave1
        ifname: eno3
        type: bond-slave
        slave_type: bond
        master: bond0
        mtu: '{{ ceph_mtu }}'
        method6: 'disabled'
        state: present
    - name: Configure eno4 as bond0 slave
      community.general.nmcli:
        conn_name: bond0-slave2
        ifname: eno4
        type: bond-slave
        slave_type: bond
        master: bond0
        mtu: '{{ ceph_mtu }}'
        method6: 'disabled'
        state: present
